### ISSUE TITLE
network 

### ISSUE THREAD

**Issue by yuanhs1996** [AllentDan/SegmentationCpp#33]
Author, I have a question for you. I want to change the network to UNet, and change the FPN in the train.cpp and resnet34.cpp files to UNet, but the training error occurs. I changed to PAN and it works. Do you know what the reason is. thank you

**Comment by AllentDan** [comment]
What is the error log?

**Comment by yuanhs1996** [comment]
(gdb) bt
#0  0x00007fb92b6fee87 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb92b7007f1 in __GI_abort () at abort.c:79
#2  0x00007fb92bf0035a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>,
    handler@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_terminate.cc:48
#3  0x00007fb92bf003c5 in std::terminate() ()
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_terminate.cc:58
#4  0x00007fb92bf00658 in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7fb98c09bf70 <typeinfo for c10::OutOfMemoryError>, dest=0x7fb928e82400 <c10::OutOfMemoryError::~OutOfMemoryError()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/build/gcc-final/x86_64-conda-linux-gnu/libstdc++-v3/libsupc++/eh_throw.cc:95
#5  0x00007fb928e9ec65 in c10::cuda::CUDACachingAllocator::DeviceCachingAllocator::malloc(int, unsigned long, CUstream_st*) ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libc10_cuda.so
#6  0x00007fb928e9fbfc in c10::cuda::CUDACachingAllocator::THCCachingAllocator::malloc(void**, int, unsigned long, CUstream_st*) ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libc10_cuda.so
#7  0x00007fb928e9ff21 in c10::cuda::CUDACachingAllocator::CudaCachingAllocator::allocate(unsigned long) const ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libc10_cuda.so
#8  0x00007fb9634cdabe in at::detail::empty_generic(c10::ArrayRef<long>, c10::Allocator*, c10::DispatchKeySet, c10::ScalarType, c10::optional<c10::MemoryFormat>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cpu.so
#9  0x00007fb97c49e3d7 in at::detail::empty_cuda(c10::ArrayRef<long>, c10::ScalarType, c10::optional<c10::Device>, c10::optional<c10::MemoryFormat>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cpp.so
#10 0x00007fb97c49e590 in at::detail::empty_cuda(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, c10::optional<c10::MemoryFormat>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cpp.so
#11 0x00007fb97c49e6e6 in at::detail::empty_cuda(c10::ArrayRef<long>, c10::TensorOptions const&) ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cpp.so
#12 0x00007fb9389861a0 in at::(anonymous namespace)::create_out(c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions const&) ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cu.so
#13 0x00007fb938a6ab86 in at::(anonymous namespace)::structured_upsample_nearest2d_out_cuda_functional::set_output_raw_strided(long, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::TensorOptions, c10::ArrayRef<at::Dimname>) ()
    at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cu.so
#14 0x00007fb963c632de in at::meta::structured_upsample_nearest2d::meta(at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cpu.so
#15 0x00007fb93898ccde in at::(anonymous namespace)::wrapper_upsample_nearest2d(at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cu.so
#16 0x00007fb93898cdd8 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double>), &at::(anonymous namespace)::wrapper_upsample_nearest2d>, at::Tensor, c10::guts::typelist::typelist<at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double> > >, at::Tensor (at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double>)>::call(c10::OperatorKernel*, c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<long>, c10::optional<double>, c10::optional<double>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cuda_cu.so
#17 0x00007fb96444eb06 in at::_ops::upsample_nearest2d::redispatch(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::optional<double>, c10::optional<double>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cpu.so
#18 0x00007fb965c05170 in torch::autograd::VariableType::(anonymous namespace)::upsample_nearest2d(c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::optional<double>, c10::optional<double>) () at /home/guestdata/yuanhongshuai/home/libtorch/libtorch/lib/libtorch_cpu.so
#19 0x00007fb965c056c9 in c10::impl::wrap_kernel_functor_unboxed_<c10::impl::detail::WrapFunctionIntoFunctor_<c10::CompileTimeFunctionPointer<at::Tensor (c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::optional<double>, c10::optional<double>), &torch::autograd::VariableType::(anonymous namespace)::upsample_nearest2d>, at::Tensor, c10::guts::typelist::typelist<c10::DispatchKeySet, at::Tensor const&, c10::ArrayRef<c10::SymInt>---Type <return> to continue, or q <return> to quit---quit
